CREATE DATABASE IF NOT EXISTS testdb;

DROP TABLE USER IF EXISTS;

CREATE TABLE USER (
    id int PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(100) NOT NULL
);